spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true                                    # SQL ???
        dialect: org.hibernate.dialect.MySQL8Dialect       # ?? ??
    hibernate:
      ddl-auto: update                                      # validate ? update? ?? ??

  datasource:
    url: jdbc:mysql://localhost:3306/book_store?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: whddbs5960